### ISSUE TITLE
Clicking Download with Mod manager not working

### ISSUE THREAD

**Issue by sevrick** [pikdum/steam-deck#10]
After uninstalling everything and installing the new version, it all seems to work except the Download with Mod Manager button for some reason it starts the Skyrim Launcher instead of downloading the mod.

**Comment by pikdum** [comment]
Which browser?

Might need to go in browser settings and make sure nxm:// links launch with Vortex.

**Comment by sevrick** [comment]
Brave is the one I use. It was working with the old version you had.

**Comment by pikdum** [comment]
Try editing the nxm lines in ~/.config/mimeapps.list:

```
x-scheme-handler/nxm=vortex.desktop
x-scheme-handler/nxm-protocol=vortex.desktop
```

You'll probably have to reboot after that.
After rebooting, check:  ~/.local/share/applications/mimeinfo.cache

**Comment by pikdum** [comment]
Not familiar with Brave, but in Firefox the config is:

General -> Files and Applications -> Applications
nxm -> Use System Handler (default)

**Comment by sevrick** [comment]
Thx that worked. Nice job btw 1st real solution I found to modding on the steam deck with skyrim.

**Comment by pikdum** [comment]
Cool, good to hear.
I'll go ahead and close this then.
