### ISSUE TITLE
vortex wont open

### ISSUE THREAD

**Issue by wolfatron39** [pikdum/steam-deck#11]
just as the title says, i installed vortex and followed the instructions, however every time i try to open it, it will show the loading icon, but then it disappears without opening vortex

**Comment by wolfatron39** [comment]
ive also tried to delete and re-install, wont work

**Comment by pikdum** [comment]
A few things to check:

* did you try restarting your steam deck?
* do you have SteamLinuxRuntime_sniper installed to internal storage?
  - $HOME/.steam/steam/steamapps/common/SteamLinuxRuntime_sniper

**Comment by wolfatron39** [comment]
I have tried restarting it, I thought the initial launch of vortex would install the runtime sniper but I can check when I have time, and no, it's the little bouncing icon next to the cursor that appears, the big one on the center of the screen never shows

**Comment by pikdum** [comment]
Anything interesting in the output if you run this?

```bash
~/.pikdum/steam-deck-master/vortex/vortex-linux launchVortex
```

**Comment by wolfatron39** [comment]
![16854334869274796129379231488530](https://github.com/pikdum/steam-deck/assets/134953331/f891a538-a391-4635-b5d2-d72885df1d66)
This is what the file looks like for me, I click on it and it asks me what I want to do, I select execute, and it does nothing

**Comment by pikdum** [comment]
You'll need to run that in the terminal (Konsole), it's a CLI:

```bash
~/.pikdum/steam-deck-master/vortex/vortex-linux launchVortex
```

**Comment by wolfatron39** [comment]
I'm sorry I'm not that savvy with all that, idk what you mean by in the terminal or it being a CLI

**Comment by pikdum** [comment]
Open up Konsole and copy-paste that command in there.

**Comment by wolfatron39** [comment]
![Uploading 16854650873026991572447820020407.jpg…]()

**Comment by pikdum** [comment]
Looks like it didn't finish uploading before you commented.

**Comment by wolfatron39** [comment]
![16854672591362984451481895832693](https://github.com/pikdum/steam-deck/assets/134953331/725feb40-dd0a-42a6-97ad-62858f7d4a3f)
There you go, sorry

**Comment by pikdum** [comment]
Interesting, looks like SteamLinuxRuntime and Proton are working.

Can you run this and give me the output too?

```
ls "/home/deck/.vortex-linux/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/"
```

**Comment by wolfatron39** [comment]
![16854685674637083271778665080084](https://github.com/pikdum/steam-deck/assets/134953331/82cf38d2-efbe-4166-b156-594cb1266200)

**Comment by pikdum** [comment]
Even more interesting, looks like Vortex didn't get installed.

Can you run this and give me the output? It should try and re-install it:

```bash
~/.pikdum/steam-deck-master/vortex/install-vortex.sh
```

**Comment by wolfatron39** [comment]
![16854694388583421621809681302095](https://github.com/pikdum/steam-deck/assets/134953331/0b4104ab-f581-4a6f-baaa-e37ed96d26ac)

**Comment by wolfatron39** [comment]
![Uploading 16854694687661351380005306716845.jpg…]()

**Comment by wolfatron39** [comment]
![16854695088321212400698030597135](https://github.com/pikdum/steam-deck/assets/134953331/a866e188-1d16-43a8-b2de-c8d24e508663)

**Comment by wolfatron39** [comment]
![Uploading 16854695459128338478773570315739.jpg…]()

**Comment by wolfatron39** [comment]
That last command seemed to fix it

**Comment by pikdum** [comment]
Okay. Looks like your internet might be a bit flaky.
From those screenshots, looks like the Proton download failed, but that's fine since it worked the first time you ran it.
Guessing the Vortex download failed the first time.

If Vortex is installed and running now, should be good.
A few things to keep in mind:
* your game and staging directory need to be set to the same drive: J: for internal, K: for sd card
* your deployment strategy should be hardlink
* (Vortex will try and walk you through these fixes)

If you run into more issues, can check the current issues.
Summarized:
* could be some issues with 'download with vortex' links, unless you're a premium member?
* somebody is running into deployment issues, could be a config issue

**Comment by wolfatron39** [comment]
Ok, thank you, I got the download path set up but it's giving me trouble with refusing to download, could he wifi, could be the fact that I never got a premium account, I'll try the downloads again when I have better internet, and if that doesn't work I guess I'll shell out for premium

**Comment by wolfatron39** [comment]
Idk, it's been a while since I was on my pc and it's never required me to have premium, on the website it still has the non premium download and the premium download still though

**Comment by wolfatron39** [comment]
Turns put it needs premium to download, idk why but I got premium and the mods finally downloaded
