### ISSUE TITLE
I can't seem to uninstall mods

### ISSUE THREAD

**Issue by sevrick** [pikdum/steam-deck#12]
When I try to remove a mod it says it failed because no deployment method is active.

**Comment by pikdum** [comment]
Did you set up a deplyoment method?

**Comment by sevrick** [comment]
I have set a staging folder. You are talking about designating a folder where the mods are stored right? I did that. Was I supposed to do the experimental hardlink? On the page where you select the path, below it, it says "No deployment method available."

**Comment by pikdum** [comment]
Make sure to press apply after picking the staging folder path.
The suggested path should work, and it'll need to be on the same drive as your game install.

After setting a valid staging folder, it should allow you to pick a deployment method.

**Comment by sevrick** [comment]
Yes I did all that. They are both on the sd card the install and the staging folder. I made folder in the root directory of the sd card called it "Moding Utilites" and then another folder in that called it "Skyrim (Vortex)". Skyrim was installed via gaming mode and on the same drive. If you have to install nexus mod manager on the same drive then I don't know how to do that. Since all the choices are made for you when you run the program.

**Comment by sevrick** [comment]
Ok I figured it out. I set the staging folder on the same SD card the game was on, but not the same drive. I didn't know steam made a separate partition on the SD cards. Thx for your help.
