### ISSUE TITLE
getting multiple vortex errors after trying to add skyrim to it

### ISSUE THREAD

**Issue by ben43210** [pikdum/steam-deck#18]
Got an error stating that vortex is unable to find skyrim.ini and skyrimprefs.ini and an error stating mods cannot be deployed.

Im not able to find any documentation or tutorials on how to make this work in linux. Please could you advise what im doing wrong?

**Comment by pikdum** [comment]
Can you post some screenshots?

After adding a game, Vortex will bring up some config issues and walk you through the fixes.

**Comment by ben43210** [comment]
Sorry I had to use Imgur as I cannot for the life of me figure out how to upload images to Github:

Cant automatically find Vortex error: https://imgur.com/bCsVkah

After specifying where skyrim is, I get these errors: https://imgur.com/wsHvJ4D

Unable to find ini file error: https://imgur.com/BJaFOgy

When trying to purge skyrim to try again, i get this error: https://imgur.com/NbehYbz

Vortex doesn't work at all unfortunately.

**Comment by pikdum** [comment]
What if you try this?
1. start Skyrim's launcher through Vortex
2. start a new game
3. exit after you hear Ralof talking

That should get you those files it's complaining about.

**Comment by pikdum** [comment]
Alternatively, could try copying them from: `~/.steam/steam/steamapps/compatdata/489830/pfx/drive_c/`

**Comment by ben43210** [comment]
First of all thank you for such a quick response. I did not realise you had to manually tell vortex where the skyrim install was. It turns out as well that I had somehow completely broken my skyrim install so even when I was telling vortex where it was, it wasn't having none of it.

Reinstalled skyrim, reinstalled vortex, Manually told vortex where skyrim is. Running the suggested mod staging folder fixed that error!

Regarding the ini files, I DID launch skyrim first but i quit the game as soon as I saw the 'bethesda presents' text therefore im guessing I did it too early for it to generate the ini files.

I think its hopefully going to work from here, if not i'll maybe post another issue. Thank you kindly!

**Comment by pikdum** [comment]
> First of all thank you for such a quick response. I did not realise you had to manually tell vortex where the skyrim install was. 

I should probably put together some better documentation on this piece.

**Comment by ben43210** [comment]
That would be handy for anyone trying to do this in the future or just something saying point it to the J: or K: drives

**Comment by pikdum** [comment]
Added some documentation, so going to close this.
