### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by UnholyScribe** [pikdum/steam-deck#20]
OK so the problem I'm having is I can install The Mods but everytime I launched the game through vortex it pops up in a little window and my controls don't work if I launch the game normalay The Mods don't show up???

**Comment by pikdum** [comment]
- What game?
- Read through the readme.
- Don't launch the game through Vortex.

**Comment by UnholyScribe** [comment]
Skyrim and I tried launching the game both ways.

**Comment by pikdum** [comment]
Skyrim SE?

Did you run the 'Skyrim Post-Deploy' shortcut before switching back to game mode?

**Comment by UnholyScribe** [comment]
I don't remember if I did that or not I will try as soon as I get off work and I have Skyrim  Legendary E

**Comment by UnholyScribe** [comment]
> Skyrim SE?
> 
> Did you run the 'Skyrim Post-Deploy' shortcut before switching back to game mode?

 Does this not work on LE?

**Comment by SirStig** [comment]
Just have to copy and paste the Skyrim deploy script and change the folder names. Cause the folder names are for SE, as the folders for LE and SE are named differently

**Comment by pikdum** [comment]
Didn't think LE was still popular, but I'd be open to a PR adding support for that too.
Then I think the only other major one we're missing is Fallout 3.

**Comment by SirStig** [comment]
> Didn't think LE was still popular, but I'd be open to a PR adding support for that too.
> 
> Then I think the only other major one we're missing is Fallout 3.

Didn’t know anyone used LE, either, but I think SE is a paid upgrade, unless you already owned LE prior to SE coming out of I remember correctly

**Comment by pikdum** [comment]
@SirStig added support for LE, so that should work now.
To test:

1. run the update shortcut, this should add a new 'Skyrim LE Post-Deploy' shortcut
2. after making sure everything looks good in Vortex, run that 'Skyrim LE Post-Deploy' shortcut
3. switch to game mode and launch Skyrim LE

**Comment by pikdum** [comment]
Going to close this, but feel free to re-open if it's still an issue.
