### ISSUE TITLE
Vortex Staging Folder

### ISSUE THREAD

**Issue by SirStig** [pikdum/steam-deck#21]
Hello!

I have been using your tool for vortex for quite a while. Ever since you switched to vortex-linux nothing works anymore.

For example, I have my games and mods all on the same main internal drive. I do not use the SD Card slot. I set the games location such as Skyrim to the game path Z:\Home\deck\.local\steam\steamapps\common\Skyrim Special Edition\ thats just me typing out the path I believe it is however no matter what game it is, or what path I set vortex always refuses to use ANY deployment mode unless I somehow created a Staging folder at Z:\Home\Vortex-Mods\ which is of course impossible because thats the user folder where you have deck or the other folder. But for whatever reason vortex refuses to see any other path as apart of the same drive the game is on.

At one point I did get it to deploy but it would only use Symlink deployment and that didn't work, no files got deployed and every single mod was always redundent. So basically I've had zero luck with this working even slightly. Vortex opens, mods download, but no deployment.

**Comment by SirStig** [comment]
Hmm disregard that. I found you linked games to the J: drive. Which does fix the staging folder issue for Skyrim. However and I know theres technically no support for Witcher 3 but any mods I add get downloaded and installed. Folders are created for the mod in the games directory however no files are actually ever deployed. It only allows me to use Symlink which is probably the issue, but annoying as every single mod is always Redundant due to no files actually being linked or anything.

**Comment by cocomunges** [comment]
I had the same issue, but for skyrim. Where did you end up pointing the staging folder to in order to fix it? UNder my J folder when selecting the staging folder doesnt have skyrim. It only has proton builds and steamlinuxruntime

**Comment by SirStig** [comment]
> I had the same issue, but for skyrim. Where did you end up pointing the staging folder to in order to fix it? UNder my J drive when selecting the staging folder doesnt have skyrim. It only has proton builds and steamlinuxruntime

You probably installed Skyrim to your Microsoft card not your Internal drive. J: points to internal drive. E: points to your external micro and card

**Comment by pikdum** [comment]
> Where did you end up pointing the staging folder to in order to fix it?

Vortex's suggested path should always work.

**Comment by SirStig** [comment]
> > Where did you end up pointing the staging folder to in order to fix it?
> 
> Vortex's suggested path should always work.

Only if when you selected where the game directory is that you used the E: or J: directory.

In my experience if you actually go to the path of the game through Z:etc instead of using the J: drive it bugs out. Vortex forces you to try to put the staging folder in Z:\home\vortex staging which of course it’ll throw an error for not allowing you to do that because it doesn’t have permissions to create a folder there. 

But it won’t recognize anything inside of Z:\home\deck\ as the same “drive” for whatever reason.

**Comment by cocomunges** [comment]
> > > Where did you end up pointing the staging folder to in order to fix it?
> > 
> > 
> > Vortex's suggested path should always work.
> 
> Only if when you selected where the game directory is that you used the E: or J: directory.
> 
> In my experience if you actually go to the path of the game through Z:etc instead of using the J: drive it bugs out. Vortex forces you to try to put the staging folder in Z:\home\vortex staging which of course it’ll throw an error for not allowing you to do that because it doesn’t have permissions to create a folder there.
> 
> But it won’t recognize anything inside of Z:\home\deck\ as the same “drive” for whatever reason.

Not quite the issue i had, the error it gave me was that the staging folder had to be on the same drive as the game install.(Which it points to my regular steam deck, steam apps folder. Not a virtualized one for some reason) And when i try pointing the staging folder to that steam deck native one, it gives me that error that they're not on the same drive. I haven't tested your solution yet though

**Comment by SirStig** [comment]
> > > > Where did you end up pointing the staging folder to in order to fix it?
> > > 
> > > 
> > > Vortex's suggested path should always work.
> > 
> > 
> > Only if when you selected where the game directory is that you used the E: or J: directory.
> > In my experience if you actually go to the path of the game through Z:etc instead of using the J: drive it bugs out. Vortex forces you to try to put the staging folder in Z:\home\vortex staging which of course it’ll throw an error for not allowing you to do that because it doesn’t have permissions to create a folder there.
> > But it won’t recognize anything inside of Z:\home\deck\ as the same “drive” for whatever reason.
> 
> Not quite the issue i had, the error it gave me was that the staging folder had to be on the same drive as the game install.(Which it points to my regular steam deck, steam apps folder. Not a virtualized one for some reason) And when i try pointing the staging folder to that steam deck native one, it gives me that error that they're not on the same drive. I haven't tested your solution yet though

That’s exactly what I just said. You must have the games directory pointing to Z:\home\deck\.local\shared\steam\steamapps\common\Skyrim Special Edition\

Which is incorrect. If the game directory is pointed to the actual directory in the Z: drive vortex bugs out and says the staging folder must be in Z:\home\ which it cannot due. Putting the staging folder using the Z: letter which you have to if the games directory is Z it’ll tell you that the staging folder is not on the same drive.

to fix this change the games directory to J:\Skyrim Special Edition\

Then use Vortexe suggested path for the staging folder which will probably be J:\Vortex-Mods

**Comment by cocomunges** [comment]
> That’s exactly what I just said. You must have the games directory pointing to Z:\home\deck.local\shared\steam\steamapps\common\Skyrim Special Edition\
> 
> Which is incorrect. If the game directory is pointed to the actual directory in the Z: drive vortex bugs out and says the staging folder must be in Z:\home\ which it cannot due. Putting the staging folder using the Z: letter which you have to if the games directory is Z it’ll tell you that the staging folder is not on the same drive.
> 
> to fix this change the games directory to J:\Skyrim Special Edition\
> 
> Then use Vortexe suggested path for the staging folder which will probably be J:\Vortex-Mods

I have skyrim installed on an external drive, but going to my E drive has nothing. Its completely empty. Do i have to install Skyrim in desktop mode? Re do the Pikdun set up and uninstall vortex(i already did that once since this issue has arised) I had mods working earlier.

**Comment by pikdum** [comment]
J: and K: are the right drives.

**Comment by cocomunges** [comment]
> J: and K: are the right drives.

Thank you, it was in my K drive. I got hardlink deployment working now

**Comment by SirStig** [comment]
> J: and K: are the right drives.

Do have a question.

I ended up using DeckMTP to just transfer all the Wither III mods which was annoying but works. I tried using STL vortex as well as your Vortex-Linux to install mods for Witcher 3. With your vortex Linux it only gave me the option for Symlinks which didn’t work. It never created any symlinks and said that all the mods were redundant well because it didn’t even actually put any files there lol.

With STL, it allowed me to do Hardlink, Symlink, and the experimental Move deploy. However all of those failed or had the same issue.

It would seem for whatever reason when it comes to Witcher 3 Vortex doesn’t have permissions or something to deploy the files in any kind of way. Skyrim works fine, haven’t tried any other games but just wondering if there’s anything to be done for this.

**Comment by pikdum** [comment]
Not sure, not familiar with Witcher 3 modding.
Entirely possible Vortex is doing something silly, though.

**Comment by SirStig** [comment]
> Not sure, not familiar with Witcher 3 modding.
> Entirely possible Vortex is doing something silly, though.

Hmm, yeah Witcher 3 is a little different. Basically deploys games into the Mods folder, sets some config files on the Bin folder, and also has a Script merger to merge script files that overlap eachother from mods.

**Comment by pikdum** [comment]
Sounds like the original issue was solved.
I'll close this and make a placeholder ticket for tracking the Witcher 3 issues.
