### ISSUE TITLE
Can’t get mods working on NV

### ISSUE THREAD

**Issue by FaultySp0rk** [pikdum/steam-deck#25]
Sorry I’m new to Linux and modding in general, I’m trying to get mods/NVSE working for new Vegas but nothing seems to be working even after using the post deploy

**Comment by SirStig** [comment]
> Sorry I’m new to Linux and modding in general, I’m trying to get mods/NVSE working for new Vegas but nothing seems to be working even after using the post deploy 

I found the issue in the post deploy script I believe. Looks like some of the code wasn’t switched from Fallout 4 to Fallout New Vegas.

If no one else fixes it I’ll try fixing it tonight and give it a test and commit a new merge for pikdum to approve.

**Comment by SirStig** [comment]
Pushed a pull request for merge. I have never modded any of the fallouts so can't say that'll fix the issue. 

However hoping it does!

**Comment by pikdum** [comment]
Merged @SirStig's PR, so it should work now after updating.

**Comment by FaultySp0rk** [comment]
Thanks I got mods working as far as I can tell but I can’t get my game to read a FalloutCustom.ini folder I need for a mod. Not sure if it’s a user error on my end

**Comment by FaultySp0rk** [comment]
Copied the files over, now the game won’t even load currently since it’s stuck on an infinite loop of what I assume is loading plugins. Not sure if I have to do a reinstall of the entire game

**Comment by pikdum** [comment]
Are you launching it from Steam Deck's game mode or from Vortex?

**Comment by SirStig** [comment]
If there’s any issues with dependencies from the mods I’d recommend using STL (SteamTinkerLaunch) to launch the game and go to the winetricks part to install them.

**Comment by FIIRETURRET** [comment]
> c++ redistributable

Is there  a correct way to install the c++ redistibutable on steam-deck other than adding it to steam as a non-steam game and running it?

**Comment by FIIRETURRET** [comment]
> I usually use protontricks to run the .exe. Can install the flatpak pretty easily on Steam Deck.

Thank you

**Comment by pikdum** [comment]
Going to go ahead and close this. Feel free to open a new issue if anybody is still having issues.
