### ISSUE TITLE
403 error when attempting to install mods

### ISSUE THREAD

**Issue by KasimAhmic** [pikdum/steam-deck#29]
I had installed Vortex using a previous version of your tools and everything worked just fine with the only issue being that if I updated Vortex, everything broke. Recently, I cleared my Vortex install and re-installed it and everything worked fine until I went to install mods.

Now every time I attempt to download a mod from Nexus Mods, I get this error:

```
Request url "..." failed with status "403".

This code is usually caused by an invalid request, maybe you followed a link that has expired or you lack permission to access it.
```

![Screenshot_20230619_185209](https://github.com/pikdum/steam-deck/assets/1304204/72a1aa9f-c667-487c-a20b-b08f6a2ecf37)

Things I've tried to resolve the issue:

1. Clear the Vortex install and re-install
2. Reboot my Steam Deck
3. Download the mods manually and add them to Vortex

**Comment by pikdum** [comment]
You're getting a 403 error from Nexus, which means access is forbidden.

Some things to verify:
* are you logged in?
* are you a premium user? (this shouldn't matter, but it might)

**Comment by KasimAhmic** [comment]
Yeah that's what I figured and I actually forgot to put that in the list of things that I tried, but I also tried logging out and logging back in and it didn't fix anything.

**Comment by KasimAhmic** [comment]
Just upgraded to a premium account and now it works flawlessly which is really weird considering I was just able to download mods like two or three days ago without having a premium account. I'll close this issue since it probably isn't related to this project at all.

**Comment by Bigkiwi12** [comment]
Just came to say was getting the same error downloading mods, upgraded to premium and fixed the issue as well
