### ISSUE TITLE
Inatall failed 

### ISSUE THREAD

**Issue by surealbus** [pikdum/steam-deck#35]
after reinstalling multiple times to verify the problem When fetching the download for  proto-GE it will timeout but will not make another attempt to get.

if your not paying attention the user may miss this happening an then vortex wont launch after removing then reinstalling it was able to successfully fetch

**Comment by pikdum** [comment]
Right, it doesn't handle network issues very well right now.
Would recommend making sure you're on a stable connection before installing.

It not properly aborting on error is tracked here - https://github.com/pikdum/steam-deck/issues/31.

**Comment by pikdum** [comment]
Should properly error out on install issues rather than continuing, which is a bit better than before.
Going to go ahead and close this - feel free to re-open if you're still having issues.
