### ISSUE TITLE
Mods Installation Folder?

### ISSUE THREAD

**Issue by Thanhpi** [pikdum/steam-deck#36]
Hi,

Is it possible to locate Default Mods Location Folder if installed on the NVME through Dolphin?

If so what is the default File Path, (Sorry, I'm a beginner)

**Comment by pikdum** [comment]
Yeah, but not sure which one you're asking for.
Can you take a screenshot of what Vortex says the directory is or something?

**Comment by pikdum** [comment]
Going to go ahead and close this, but feel free to re-open if you still need help.

Most folder locations you'll want are in ~/.vortex-linux/ somewhere, probably in compatdata.
