### ISSUE TITLE
12 hours to install pre-downloaded collection

### ISSUE THREAD

**Issue by brianx87** [pikdum/steam-deck#38]
Tried to install a collection, but the installation has repeated itself more than a dozen times with each restart only installing several GB of a 80GB install. The collection is already installed on my PC so all I had to do was copy over the downloads and mod install folder but doing that has caused each mod of a 500+ mod install to trigger a replace mod/create variant dialog. Reinstalled Vortex and tried again this time using only the downloads folder so Vortex can install the mods itself, it partially worked except it's been 12+ hours and it's still giving me issues with deployment and dependencies not fulfilled., restarting the install process every time.

**Comment by pikdum** [comment]
I've noticed collection downloads can take a very long time, but I'm not sure there's anything that can be done to improve that outside of Vortex.
