### ISSUE TITLE
Potential script to revert back to unmodded state?

### ISSUE THREAD

**Issue by annathepiper** [pikdum/steam-deck#39]
Hi, I came across this repo last night when trying to get Vortex updated on my Steam Deck. I'd been previously using steamtinkerlaunch, but running into a lot of issues getting Vortex to update properly. So I decided to try a clean re-install and use this set of scripts instead. First off let me say this worked _delightfully_, thank you so much for this work. <3

Second, I have a question and wanted to ask for a sanity check here. I currently have _two_ playthroughs going in Skyrim on my Deck, one with mods and one without. I'd like to be able to swap back and forth between them. If I'm understanding the Skyrim post deploy script correctly, you're basically doing the following, right?

1. Renaming SkyrimSELauncher.exe to _SkyrimSELauncher.exe
2. Renaming skse64_loader.exe to SkyrimSELauncher.exe
3. Copying load order and plugin info into the specified directories

So if I was to duplicate your post deploy script and just reverse the renaming of the launchers, so that SkyrimSELauncher.exe is set back to the original launcher, that would set me back to a vanilla state, yes? I've _manually_ tested this and it seems like it works okay, but I wanted to doublecheck that I'm not missing something. :)

Thanks in advance! And again, thank you for the work, you've saved my bacon with getting a current working Vortex back onto my device!

**Comment by pikdum** [comment]
Sounds right, yeah.

**Comment by annathepiper** [comment]
> Sounds right, yeah.

Thank you very much! I can confirm since I put this up that this seems to be working splendidly. I use your script to activate my modded playthrough, and then use the one I made to reverse what it did when I want to switch to the unmodded one. I appreciate the confirmation!

Please feel free to close out this issue.

**Comment by annathepiper** [comment]
Or hmm I guess github will let me do that, Doing so now. :)
