### ISSUE TITLE
Do I need to keep the external directories if I don't have an SSD installed?

### ISSUE THREAD

**Issue by annathepiper** [pikdum/steam-deck#40]
Second sanity check please, opening a second issue for this because it's not directly related to my first question, but wanted to ask about this BEFORE I make any more local changes to your scripts on my device.

I have no external SSD in my Deck, I bought the highest tier one and currently have no space constraints, so I haven't had to get an external SSD. So when I run your scripts, I'm seeing an error get thrown when it tries to copy stuff out to the APPDATA_EXTERNAL path your script sets up.

Would there be any problem with my removing the parts of the script relevant to that directory? It doesn't seem to be having an impact on my ability to set up Skyrim otherwise, as near as I can tell.

Again, thanks very much in advance!

**Comment by pikdum** [comment]
Those errors are just for logging, they should be ignored and the rest of the script should proceed.
If not, then it's probably a bug.

**Comment by annathepiper** [comment]
Noted and thank you! I'll close this out.
