### ISSUE TITLE
Not running anymore.

### ISSUE THREAD

**Issue by Demonshadows9** [pikdum/steam-deck#41]
I had it installed and running at first but was having some issues with vortex so I uninstalled everything and now when i redownload the file and go to open it, it just asks what app i want to use to open it instead of asking to extract the file like before.

**Comment by pikdum** [comment]
Just shipped an update that might help fix things.

1. run update shortcut
2. re-run the vortex install script

**Comment by Demonshadows9** [comment]
I just tried again and it's still not working. I don't think my issue is your files, I think it's something on my end. I'm not sure. The file isn't launching to where I can extract it anymore
![Uploading 20230822_163759.jpg…]()

**Comment by pikdum** [comment]
Looks like your screenshot upload got interrupted, and I'm not quite sure what you mean.

**Comment by Demonshadows9** [comment]
Sorry I'm new to this website still. So I downloaded and installed you script the first time and it ran with no issues but then I was having issues with vortex cause it wasn't loading the mods and it said it needed to update vortex. After having issues for a bit I went and followed your uninstall instructions to remove everything. After it was all removed I redownload your script and go to run it and not it doesn't pop up the menu to extract the files like before. It now asks me what program I want to use to run/open the file and selecting Konsole or anything doesn't work and I can't get the file to run at all

**Comment by Demonshadows9** [comment]
![20230822_163759](https://github.com/pikdum/steam-deck/assets/142359940/44e2d15b-c230-4959-8b4c-2ccec94e874b)

**Comment by Demonshadows9** [comment]
Idk if maybe i deleted too much or the wrong thing. 

![20230822_165754](https://github.com/pikdum/steam-deck/assets/142359940/ed650a32-d42e-4f0d-9ec5-7fdcef726640)
![20230822_165742](https://github.com/pikdum/steam-deck/assets/142359940/aaaad000-34e9-428e-8935-d19d63b6bcf0)

**Comment by pikdum** [comment]
Ah, I think I see. For some reason it's downloading as `install.desktop.download` instead of just `install.desktop`.

Are you able to rename it to `install.desktop`?

**Comment by Demonshadows9** [comment]
I just tried that and nope it's still asking for an application to open it

**Comment by Demonshadows9** [comment]
![20230822_172554](https://github.com/pikdum/steam-deck/assets/142359940/3301f3f1-68b7-46f8-b42d-53bf5c451374)

**Comment by pikdum** [comment]
Hm, not sure. Mine still runs when double clicking.

You could try copying that curl piece into Konsole and install manually like that, though:

```
curl https://raw.githubusercontent.com/pikdum/steam-deck/master/install.sh | bash -s --
```

**Comment by Demonshadows9** [comment]
> Hm, not sure. Mine still runs when double clicking, even as install.desktop.download.
> 
> You could try copying that curl piece into Konsole and install manually like that, though:
> 
> ```
> curl https://raw.githubusercontent.com/pikdum/steam-deck/master/install.sh | bash -s --
> ```

Oh god thanks bub. I just copied and ran that curl string in the konsole and it added the vortex Downloader back to my desktop. Now I can try to mod my Baldur's Gate 3 again!
