### ISSUE TITLE
No longer launches

### ISSUE THREAD

**Issue by sw201444** [pikdum/steam-deck#42]
Was working fine, installed a mod from fallout 4 itself. It's disabled a ton of mods and I can't open vortex to repair them.

Will bounce then stop. I can run the post launch stuff. I've ran the update "success!" no change. I've ran the installer. "success!" no change.

**Comment by pikdum** [comment]
I'm thinking a Vortex auto-update broke things.
Will look into it, but there might not be much I can do.

**Comment by pikdum** [comment]
Still looks working on my deck, but somehow I've broken proton on my desktop. :)

Shipped an update that should:
* have properly error out if vortex install fails
* update to latest vortex + proton-ge + vortex-linux

To give it a try:
* run the update script
* maybe try re-running the vortex install script

**Comment by sw201444** [comment]
Looks like it opens now. 

But in my troubleshooting I completely reinstalled it so now it’s a new instance, yaaaaay. 

Is there a way to disable the vortex auto update to prevent any issues in the future?

**Comment by sw201444** [comment]
I stand corrected. 

I closed vortex, got a warning it would update when closed. It no longer opens.. again. 

Re-ran your updater and it opened again. I found the option, Disabled the auto updates (oh no! Not my online features!) but it seems to be working.

**Comment by FaultySp0rk** [comment]
Damn I think I missed my window to turn off the auto updater cuz now mine doesn’t open and I’d rather not reinstall. Guess I’ll wait for a bit for a fix

**Comment by pikdum** [comment]
Pushed a fix, should work again after running the update script.

Haven't tested on Steam Deck, though, only Linux desktop.

**Comment by FaultySp0rk** [comment]
Thanks for all the hard work. I had a question, how do you go about getting the launcher to pop up with Protontricks? I tried figuring out but I’m dumb with Linux

**Comment by pikdum** [comment]
> how do you go about getting the launcher to pop up with Protontricks?

1. install protontricks
2. navigate to skyrim's directory with your file explorer
3. right click, open with protontricks

> edit: Seems like the update is still not working on the Deck
bummer
