### ISSUE TITLE
Update script stuck at downloading Proton

### ISSUE THREAD

**Issue by CurlyBoy** [pikdum/steam-deck#43]
Just trying to run the update script but it won't continue after `Downloading Proton...`. Full log in the pastebin

https://pastebin.com/5Y2U2Kz7

**Comment by pikdum** [comment]
It can take a while, since it's ~500 MB. Was just running into this myself.
I'm going to see if using a library instead of fetch will be quicker.

**Comment by pikdum** [comment]
Tweaked some things, should be a bit more reliable.
If it's still stuck, can close and re-try.

**Comment by CurlyBoy** [comment]
Yeah I think it worked now, thanks!
