### ISSUE TITLE
Unable to get Fallout4custom.ini changes to transfer to the gme

### ISSUE THREAD

**Issue by FaultySp0rk** [pikdum/steam-deck#45]
Is there a way to get the games to transfer/read ini file changes? Trying to get mods to work but a majority of them need ini tweaks that don’t seem to transfer over using post deploy or manually. Not sure if there’s a solution. Thanks for the hard work

**Comment by pikdum** [comment]
You should be able to find all of Vortex's files somewhere in ~/.vortex-linux/compatdata/.
Probably go up the C: drive to the user's Documents folders or similar.

**Comment by FaultySp0rk** [comment]
I’m very newish to this stuff so bare with me, whenever I do a post deploy after installing a mod it seems to reset the ini tweaks I did on the main file. Would changing it in .vortex-Linux keep the changes?

**Comment by pikdum** [comment]
Looks like that post-deploy script copies over everything in `$HOME/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4`.
