### ISSUE TITLE
Can someone please help with game location?

### ISSUE THREAD

**Issue by papawheelie** [pikdum/steam-deck#46]
I'm trying to manually set the location of my game but I just cannot seem to find it. Can anyone give me specific instructions because I'm very lost. Any help would be amazing!

**Comment by pikdum** [comment]
J: is internal drive, K: is SD card.

**Comment by papawheelie** [comment]
> J: is internal drive, K: is SD card.

I don't have an SD card, so I'm still not sure where the path is. I'm trying to mod starfield, I hit manage and it tells me to select the game path. This is all I see. is the drive labeled "/" the J drive you're talking about?
![PXL_20230906_221035654](https://github.com/pikdum/steam-deck/assets/107367481/15b3e11b-d9e2-4f61-bd47-ebb07641919c)

**Comment by pikdum** [comment]
Expand My Computer in the left to see the drives.

**Comment by pikdum** [comment]
Also, I'm guessing Starfield will require a bit more effort to mod.

We have post-deploy shortcuts for other Bethesda games to copy files to their proper locations, and Starfield might need something similar.

https://github.com/pikdum/steam-deck/blob/master/vortex/skyrim-post-deploy.sh could be a starting point.

**Comment by papawheelie** [comment]
> Also, I'm guessing Starfield will require a bit more effort to mod.
> 
> We have post-deploy shortcuts for other Bethesda games to copy files to their proper locations, and Starfield might need something similar.
> 
> https://github.com/pikdum/steam-deck/blob/master/vortex/skyrim-post-deploy.sh could be a starting point.

Alright thanks! I figured out the J file thing, but after restarting my deck vortex won't open anymore. I tried running the updater but even after that it's not opening. Am I supposed to do something specific before I open vortex?

**Comment by pikdum** [comment]
Shouldn't need to, no.
