### ISSUE TITLE
J: Drive not linked

### ISSUE THREAD

**Issue by BrandoniSpumoni** [pikdum/steam-deck#49]
Sorry, I am not experienced with linux but i assumed that the wording of the guide meant that the J drive would by linked to my steamdeck's internal drive and at least Skyrim would be visible there? Or something of the sort. 

Anyways when i open vortex and go to add skyrim SE this is what appears in the J drive:

![image](https://github.com/pikdum/steam-deck/assets/92545223/4c4aa5be-ea41-40b3-82f5-30be5daa376c)

Obviously I missed something somewhere...sorry if the solution is staring me in the face...

**Comment by BrandoniSpumoni** [comment]
I realized i should add Skyrim is not on the SD card drive either. I installed it on my internal drive though so that's expected.

**Comment by pikdum** [comment]
Interesting, what's in all those other drives?

This script only intentionally sets J and K:

https://github.com/pikdum/steam-deck/blob/cdf89a1b2b77782f1499c4a95b9e32aebcc0ef93/vortex/install-vortex.sh#L43-L49

**Comment by BrandoniSpumoni** [comment]
Sorry for the late reply i ended up fixing my issue. Basically if you have any other drives connected to your steam deck other than the internal and SD card it gets confused and links them all to the wrong place. Disconnecting the drives and starting over solved the problem. However a side problem i noticed is if you accidentally use the in game mod manager at all it sort of breaks everything.
