### ISSUE TITLE
steamtinkerlaunch.sh errors

### ISSUE THREAD

**Issue by SneedusSnake** [pikdum/steam-deck#5]
I'm not sure whether this issue belongs here or in steamtinkerlaunch repo, but during the process of vortex installation through `install-vortex.desktop`, at some point console yields following error: 
`/home/deck/stl/prefix/steamtinkerlaunch: line 3744: [: : integer expression expected`
It still finishes and vortex icon appears on desktop. When clicking on it, it's icon appears on task bar for a few seconds and nothing else happens. When I try to launch `launch-vortex.sh` to see what the problem is, the aforementioned error is shown as well as another one after it:
`/home/deck/stl/prefix/steamtinkerlaunch: line 14994: : command not found`
after which the script crashes.

**Comment by pikdum** [comment]
If you can add `set -x` somewhere near the top of ~/stl/prefix/steamtinkerlaunch and run `~/stl/prefix/steamtinkerlaunch vortex start`, might be able to figure out exactly what it's trying to do.

**Comment by SneedusSnake** [comment]
> If you can add `set -x` somewhere near the top of ~/stl/prefix/steamtinkerlaunch and run `~/stl/prefix/steamtinkerlaunch vortex start`, might be able to figure out exactly what it's trying to do.

the output of that command is rather huge with no apparent errors:
[launch.log](https://github.com/pikdum/steam-deck/files/11415161/launch.log)
However running launch-vortex.sh have this at the end:
```
writelog ERROR 'startVortex - VORTEXEXE '\''/home/deck/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe'\'' not found! - exit'
+ LOGONE=404,ERROR,SKIP,WARN,CREATE
+ '[' -n '' ']'
+ '[' -z 2 ']'
+ '[' 2 -eq 1 ']'
+ '[' 2 -eq 2 ']'
+ '[' -z /home/deck/.config/steamtinkerlaunch/logs/steamtinkerlaunch/id/31337.log ']'
+ tee -a /dev/shm/steamtinkerlaunch/steamtinkerlaunch.log /home/deck/.config/steamtinkerlaunch/logs/steamtinkerlaunch/id/31337.log
++ date
+ echo 'Sun May  7 04:57:03 PM MSK 2023 ERROR - startVortex - VORTEXEXE '\''/home/deck/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe'\'' not found! - exit'
+ '[' -n '' ']'
+ exit

```

**Comment by pikdum** [comment]
Looks like the Vortex install failed. I'll try testing a clean install later today, to see if it's totally broken or not.

If you want to try, the only thing I can think of is to wipe + reinstall: https://github.com/pikdum/steam-deck/issues/3#issuecomment-1515523080

**Comment by pikdum** [comment]
Were you able to resolve?

Recently pushed a fix for some other issues: https://github.com/pikdum/steam-deck/issues/7#issuecomment-1545147053

**Comment by SneedusSnake** [comment]
I have tried reinstalling it, but it didn't resolve the issue for me. Will try again with the fix in mind.

**Comment by SneedusSnake** [comment]
Fresh reinstall helped this time, thanks! You can close the issue, one question though: do I have to turn off vortex auto-updates in order for it not to break eventually?

**Comment by pikdum** [comment]
> do I have to turn off vortex auto-updates in order for it not to break eventually?

Yeah, haven't figured out how to get Vortex 1.8 to run on Steam Deck.
So if it auto-updates to 1.8, it'll break right now.

**Comment by pikdum** [comment]
Closing since the original issue was resolved.
