### ISSUE TITLE
Won't launch anymore

### ISSUE THREAD

**Issue by Conmansigner** [pikdum/steam-deck#56]
Vortex was working on steam deck as of 11/05/23, and I'm suspecting it auto-updated and broke something. As of now the icon will bounce and then nothing will happen.

**Comment by pikdum** [comment]
Can't reproduce on my end - maybe reinstalling would fix?

**Comment by Conmansigner** [comment]
> Can't reproduce on my end - maybe reinstalling would fix?

Managed to get it on saturday, had to fully Uninstaller vortex and reinstall all of it, then turn autoupdate off

**Comment by pikdum** [comment]
Just bumped up the Proton and Vortex versions, so running the Update shortcut should fix this for everybody.
