### ISSUE TITLE
Why .desktop file for install?

### ISSUE THREAD

**Issue by SomeAcnt** [pikdum/steam-deck#6]
I noticed in reddit that someone is stuck with installing this tool. For a layman, it should have seemed like there is something wrong with the desktop file. Yet the problem seems to lie in some unknown bug. 
Wouldn't making a proper flatpak and packaging it guarantee better experience? Desktop file is quite unwieldy as a way to run an installer.

**Comment by pikdum** [comment]
Mostly inspired by https://github.com/CryoByte33/steam-deck-utilities.

You can also install with `curl | bash`:

```
curl https://raw.githubusercontent.com/pikdum/steam-deck/master/install.sh | bash -s --
```
