### ISSUE TITLE
loadorder.txt and plugins.txt files don't change after running FNV Post Deploy once

### ISSUE THREAD

**Issue by Eevim** [pikdum/steam-deck#60]
Hello, I believe I have an issue where the loadorder.txt and plugins.txt files don't change after running FNV Post Deploy once. They only change after the first execution of FNV Post Deploy, but fail to change on any subsequent executions as far as I can tell. Leading to the load order of my mods being wonky and the game running improperly. I am trying to download this modpack for New Vegas found here:

https://next.nexusmods.com/newvegas/collections/jscbqj

I had a discussion with the creator of this modpack (https://next.nexusmods.com/newvegas/collections/jscbqj?tab=comments&commentId=65849) about my difficulties getting the game to run properly, and he told me that the glitches I was experiencing in-game were entirely unique to steam deck users as far as they could tell, and I believe said glitches are caused by the loadorder.txt and plugins.txt files failing to change. 

I hope a solution can be found for this issue!

**Comment by Eevim** [comment]
If anyone has 18 GB to spare... perhaps it would be worthwhile for someone here that's more tech savvy than myself to try downloading this modpack?

**Comment by Kupok-Natsu** [comment]
If when running the deployment script, do you see a No File or Directory error? The scripts seem to be using an older directory structure for Steam Deck's sd card.

Backup files before making any changes you make to the scripts located in /home/deck/.pikdum/steam-deck-master/vortex/ but try opening the New Vegas deployment scripts with kate, and replacing any instance of "mmcblk0p1" with "deck/SdCardForDeck" and running the desktop links again.

**Comment by DiscoDaz** [comment]
I have the exact same problem after running the last kiss lite collection for new Vegas, the load order is goosed so all my mods are conflicting and not working correctly. The game installed on the internal storage. 

Did you manage to resolve this?

**Comment by DiscoDaz** [comment]
I fixed it. Manually copy the plugin and load order .txt files to the internal or external drive. Game is working flawlessly now

**Comment by Eevim** [comment]
> I fixed it. Manually copy the plugin and load order .txt files to the internal or external drive. Game is working flawlessly now 

Could you elaborate on this? What folders did you copy them to?

**Comment by DiscoDaz** [comment]
Find the loadorder.txt and plugin.txt on the virtual C drive and manually copy, then find the same on files on the steam decks drive (mine was the Z drive but could be different for you) and paste those two files and choose overwrite.

**Comment by fenehan71** [comment]
To make all thigs Clear you need to copy 2 files from:
/home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/falloutnv/
And paste it here:
/home/deck/.steam/steam/steamapps/compatdata/22380/pfx/drive_c/users/steamuser/AppData/Local/falloutnv/
remembering this is if you instaled the game on SSD on sd card the path gonna be diferent.

**Comment by pikdum** [comment]
Might be fixed with the latest few commits - if not feel free to re-open.
