### ISSUE TITLE
support new steam deck sd card path

### ISSUE THREAD

**Issue by pikdum** [pikdum/steam-deck#62]

**Comment by DiscoDaz** [comment]
Will this resolve the issue with internal stored games too? My post deployment file for new Vegas isn't updating the plugin and load order files.

**Comment by RachelWofle** [comment]
It would be grand to support an arbitrary Steam Library path too, my Deck has an upgraded SSD with a dedicated games partition. Currently trying to tinker with winetricks to add a drive letter that goes to the mount path.

**Comment by pikdum** [comment]
You should be able to add them with symlinks:

https://github.com/pikdum/steam-deck/blob/ab05241b7e6af876b7bb9483f257ffe9439b56a2/vortex/install-vortex.sh#L45-L51
