### ISSUE TITLE
Oblivion post-deploy script not working correctly

### ISSUE THREAD

**Issue by merewolf** [pikdum/steam-deck#67]
Hi, oblivion-post-deploy script copies plugins.txt file from "$HOME/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Oblivion/" into  game installations Local folder. That folder however already contains Plugins.txt file with a capital letter. Because of this, instead of one file that directory has plugins.txt next to Plugins.txt and the game defaults to using Plugins.txt.
This causes any mods that use plugins to not load correctly.

As a workaround, deleting Plugins.txt fixes the problem completely. A permanent solution would perhaps be to delete existing plugins.txt from the directory regardless of case?

**Comment by pikdum** [comment]
I've heard of this issue happening with Skyrim too - not entirely sure where the Plugins.txt is coming from, though.

**Comment by pikdum** [comment]
Latest update should've fixed. Feel free to re-open if it hasn't.
