### ISSUE TITLE
Vortex unresponsive after a few seconds of opening

### ISSUE THREAD

**Issue by PsychoPsojic** [pikdum/steam-deck#68]
On first install of vortex everything was working great, thought it was conflicting with gaming mode so I deleted it. Figured out that my gaming mode issue was not related. 

Reinstalled this and now vortex becomes visually unresponsive, when I maximize the program it goes black. I can sill click the x to close the program so I'm thinking vortex is working but not showing feedback to inputs.

Not sure whats going on as my first install was great, but on the second it broken, need some help with getting this working again.

I've tried restarting, reinstalling, updating, reinstalling with install-vortex.sh, nothing seems to work.

![Screenshot_20240309_033344](https://github.com/pikdum/steam-deck/assets/115117658/60f011e3-6cde-49b6-b40f-19210126a950)

![Screenshot_20240309_033413](https://github.com/pikdum/steam-deck/assets/115117658/022c5daf-b580-4543-8935-96cd7a1ebeb2)

**Comment by pikdum** [comment]
Interesting. Have you tried resizing the window at all?

**Comment by PsychoPsojic** [comment]
Yes, it just goes black. I made a video showing what vortex does. Also steam stops working and "steam button" + X doesn't bring up the keyboard until I restart Steam. 

https://github.com/pikdum/steam-deck/assets/115117658/0433cb74-d0c9-4e7c-9e53-9adaaf9cc0e2

https://drive.google.com/file/d/1afAB4Cm9VgRk-7qH67GAbfqIh7SdfSU-/view?usp=sharing

**Comment by pikdum** [comment]
Very weird. What Steam Deck release channel are you on?
I'm on Beta, and not able to reproduce.

**Comment by PsychoPsojic** [comment]
Hey sorry, I should have updated this earlier. I uninstalled Skyrim SE, deleted its folder, deleted your program and vortex, reinstalled everything and its back to working again. Thank you for your responses.
