### ISSUE TITLE
Fallout NV Post-Deploy Script issue

### ISSUE THREAD

**Issue by SaltyWhaler** [pikdum/steam-deck#70]
The variables for the Local AppData folders are all lowercase: `falloutnv` but the Steam version of FONV is typed like this: `FalloutNV`

```
APPDATA_VORTEX="$HOME/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/falloutnv/"
APPDATA_INTERNAL="$HOME/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/users/steamuser/AppData/Local/falloutnv/"
APPDATA_EXTERNAL="/run/media/mmcblk0p1/steamapps/compatdata/22380/pfx/drive_c/users/steamuser/AppData/Local/falloutnv/"
```

This causes the post-deploy script to put the load order file into the wrong folder and as a result, mods won’t load. I was able to fix this by simply changing the post-deploy script to point towards `FalloutNV` instead.

**Comment by pikdum** [comment]
Interested in opening a pull request?

**Comment by SaltyWhaler** [comment]
Sorry for late response - done and done!
