### ISSUE TITLE
Fallout 4 Post Deploy lacks permissions?

### ISSUE THREAD

**Issue by finnishamerican** [pikdum/steam-deck#72]
+ FALLOUT4_INTERNAL='/home/deck/.steam/steam/steamapps/common/Fallout 4/'
+ FALLOUT4_EXTERNAL='/run/media/mmcblk0p1/steamapps/common/Fallout 4/'
+ f4se_setup '/home/deck/.steam/steam/steamapps/common/Fallout 4/'
+ '[' -d '/home/deck/.steam/steam/steamapps/common/Fallout 4/' ']'
+ '[' -f '/home/deck/.steam/steam/steamapps/common/Fallout 4/f4se_loader.exe' ']'
+ '[' -f '/home/deck/.steam/steam/steamapps/common/Fallout 4/Fallout4Launcher.exe' ']'
+ cd '/home/deck/.steam/steam/steamapps/common/Fallout 4/'
+ cmp --silent -- f4se_loader.exe Fallout4Launcher.exe
+ f4se_setup '/run/media/mmcblk0p1/steamapps/common/Fallout 4/'
+ '[' -d '/run/media/mmcblk0p1/steamapps/common/Fallout 4/' ']'
+ APPDATA_VORTEX=/home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4
+ APPDATA_INTERNAL=/home/deck/.local/share/Steam/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/
+ APPDATA_EXTERNAL=/run/media/mmcblk0p1/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/
+ echo 'Copying loadorder.txt and plugins.txt'
Copying loadorder.txt and plugins.txt
+ mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/
+ mkdir -p /run/media/mmcblk0p1/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/
mkdir: cannot create directory ‘/run/media/mmcblk0p1’: Permission denied
+ true
+ cp /home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/loadorder.txt /home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/Plugins.fo4viewsettings /home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/plugins.txt /home/deck/.local/share/Steam/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/
+ cp /home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/loadorder.txt /home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/Plugins.fo4viewsettings /home/deck/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/plugins.txt /run/media/mmcblk0p1/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/
cp: target '/run/media/mmcblk0p1/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/': No such file or directory
+ true
+ echo 'Success! Exiting in 3...'
Success! Exiting in 3...
+ sleep 3

Fails to create a directory and certain f4se mods just don't seem to run. Trying to chase down why.

edit: it’s mainly HUD/overlay mods like Condition Boy and Gas Masks of the Wasteland/Nuclear Winter.

**Comment by acovaci** [comment]
Judging by the post time, I assume you're running next gen?

If yes, just add two extra lines in `/home/deck/.pikdum/steam-deck-master/vortex/fallout4-post-deploy.sh`:

```bash
echo "Copying loadorder.txt and plugins.txt"
mkdir -p "$APPDATA_INTERNAL" || true
mkdir -p "$APPDATA_EXTERNAL" || true
cp "$APPDATA_VORTEX"/* "$APPDATA_INTERNAL" || true
cp "$APPDATA_VORTEX"/* "$APPDATA_EXTERNAL" || true
cp "$APPDATA_VORTEX"/plugins.txt "$APPDATA_INTERNAL"/Plugins.txt || true # THIS
cp "$APPDATA_VORTEX"/plugins.txt "$APPDATA_EXTERNAL"/Plugins.txt || true # THIS

echo "Success! Exiting in 3..."
sleep 3
```

Basically the `plugin.txt` file is now capitalised

**Comment by acovaci** [comment]
Huh, never mind, I completely missed the permission lines. I assume that's because you don't have an SD card inserted?

You can safely ignore those errors if so.

The reason for not deploying is still most likely my comment above.

**Comment by pikdum** [comment]
Maybe this is the same issue as https://github.com/pikdum/steam-deck/issues/67 then?

**Comment by pikdum** [comment]
Latest update should've fixed. Feel free to re-open if it hasn't.
