### ISSUE TITLE
Fallout 4 Deploy

### ISSUE THREAD

**Issue by intiek** [pikdum/steam-deck#8]
Hey bud. Im attempting to modify the script for Fallout 4. Am I on the right track?
[https://pastebin.com/dmbRjqfg](https://pastebin.com/dmbRjqfg)

**Comment by intiek** [comment]
> Hey bud. Im attempting to modify the script for Fallout 4. Am I on the right track? https://pastebin.com/dmbRjqfg

After messing with it for awhile I got it working! If anyone is interested feel free to use it.

**Comment by Afrodinho** [comment]
What exactly does the post-deploy do? Help ensure the load order and plugins are loaded by the game correctly? If that is the case, wouldn't we need a post-deploy for every game we mod?

**Comment by pikdum** [comment]
> If anyone is interested feel free to use it.

Added.

Made some changes to how Vortex is installed, though, so upgrading will require a full uninstall + reinstall.
