### ISSUE TITLE
how to load vortex-linux prefix in protontricks OR install dotnet runtimes to the prefix

### ISSUE THREAD

**Issue by Gildedter** [pikdum/steam-deck#82]
title says it, I need to install some dotnet runtimes so that Pandora can work once linked in vortex tools

**Comment by Gildedter** [comment]
Found a workaround using protontricks, disregard

**Comment by Mr-Benedict** [comment]
@Gildedter It would be nice to know what workaround have you found :)

**Comment by Gildedter** [comment]
add the desktop shortcut to steam and run it, then restart the deck, it will now appear under protontricks

**Comment by mellowcicada** [comment]
this unfortunately hasn't worked for me. as soon as I delete then link the compatdata from ~/.vortex-linux, I stop being able to see vortex-linux in protontricks

**Comment by pikdum** [comment]
The `vortex-linux` CLI is located at: ` ~/.pikdum/steam-deck-master/vortex/vortex-linux`

```console
$ ~/.pikdum/steam-deck-master/vortex/vortex-linux help
Usage: vortex-linux [options] [command]

Options:
  -V, --version                      output the version number
  -h, --help                         display help for command

Commands:
  downloadProton <downloadUrl>       Download Proton
  setProton <protonBuild>            Set Proton Build
  downloadVortex <downloadUrl>       Download Vortex
  installVortex <vortexInstaller>    Install Vortex
  launchVortex [args...]             Launch Vortex
  setupVortexDesktop                 Setup .desktop entry for Vortex
  getConfig                          Output config
  setConfig <key> [value]            Set config key
  protonRunUrl <downloadUrl> [args]  Download and run an .exe
  help [command]                     display help for command
  ```
  
  There's not a command exposed to run an .exe directly, but `protonRunUrl` is used to install .NET for Vortex: https://github.com/pikdum/steam-deck/blob/bd3b6a00af9018238cdb277c2ca131f47d414d43/vortex/install-vortex.sh#L39
  
  Might work for your use-case.
  
  If not, I could probably add a `protonRun` command to vortex-linux.

**Comment by mellowcicada** [comment]
for context, running tools like [DynDOLOD](https://dyndolod.info/Installation-Instructions), [Synthesis](https://github.com/Mutagen-Modding/Synthesis), etc. inside Vortex depend on Visual C++ Redistributables and various .NET libraries, so a tool like protonRun to get those working would be amazing

**Comment by mellowcicada** [comment]
for context, running tools like [DynDOLOD](https://dyndolod.info/Installation-Instructions), [Synthesis](https://github.com/Mutagen-Modding/Synthesis), etc. inside Vortex depend on Visual C++ Redistributables and various .NET libraries, so a command like protonRun to get those working would be amazing

**Comment by pikdum** [comment]
This should work for those, then:

```
~/.pikdum/steam-deck-master/vortex/vortex-linux protonRunUrl "https://aka.ms/vs/17/release/vc_redist.x64.exe"
```

**Comment by mellowcicada** [comment]
thank you, works great!

but I'm still running into roadblocks that I otherwise wouldn't if I could figure out how to get vortex recognised by protontricks.
e.g. trying to run [SSEEdit](https://www.nexusmods.com/skyrimspecialedition/mods/164) inside vortex returns this 
![Screenshot_20241020_093223](https://github.com/user-attachments/assets/08d80932-7b91-4bc3-a7d4-fa98421d1f3f)

a friend who's been helping me said: "if you're using pikdum those tools won't detect the registry keys for skyrim install, you'll have to export it via protontricks regedit (selecting skyrim prefix), then using the work around from earlier, important said registry key"

is there any other way to achieve this? maybe via the CLI?

**Comment by pikdum** [comment]
Maybe something like this:

```
STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/root" STEAM_COMPAT_DATA_PATH="$HOME/.vortex-linux/compatdata" $HOME/.vortex-linux/proton-builds/active/proton run regedit
```

**Comment by mellowcicada** [comment]
that did it, thank you!
