### ISSUE TITLE
doesn't seem to work at all

### ISSUE THREAD

**Issue by Maz111111** [pikdum/steam-deck#9]
I saved install.desktop with a right click and then double clicked on it.
So far so good. As a result I have 4 icons on the desktop. Vortex is in and getting started.
Judging by all the descriptions, everything should work as usual from then on.
However, when adding Fallout 4, vortex reports that it cannot find the path. I then manually set the path to j:/Fallout4/.
1. Vortex reports that there is no fallout4.ini and no fallout4prefs.ini. Both files are present in the folder vortex is mentioning in the message.
2. Only manual download of Nexusmods works. When downloading via Modmanager, vortex reports Download failed - A click on "more" shows "status 403".
3. The Fix for chrome does not work (vortex cannot find the chrome preferences file) - But even downloads via firefox don't work (same error)
4. You can insert mods manually - none works - the necessary files are not to be found in the fallout4 folder despite "enable" and clicking on "Fallout4 Post deploy".
5. Upon reboot, vortex reports "Primary Tool for Fallout 4 is unavailable".

If I'm not doing anything wrong (I'm grateful for every tip) there seems to be something wrong with the current release.

I saw videos on youtube where everything worked as expected. However, that was probably an older version of your tool. In this respect, I do not rule out that the fault lies with me or my deck.

Regardless of my problems - thank you very much for the great project and the great work!

**Comment by pikdum** [comment]
Let me test some things, entirely possible I missed something and it's completely broken.

**Comment by Afrodinho** [comment]
For me, I can download mods via Nexus as if I were on Windows. I click the Vortex button and the mod is downloaded to my vortex downloads folder. 

 >4. You can insert mods manually - none works - the necessary files are not to be found in the fallout4 folder despite "enable" and clicking on "Fallout4 Post deploy".

The issue I am having is related to deployment. My staging folder is located on the C drive by default while my Skyrim is located on Z drive. I'm going to do the obvious and change the location to see if that fixes my issue. Maybe our issues are related?

So far this version seems a lot more stable than previous versions. This seems more native to Linux. I'm experiencing less stutters and issues than I was before and the app launches faster than ever.

**Comment by pikdum** [comment]
> The issue I am having is related to deployment. My staging folder is located on the C drive by default while my Skyrim is located on Z drive. I'm going to do the obvious and change the location to see if that fixes my issue.

Yeah, you'll want staging on the same drive as your game. Vortex's 'suggested fix' should work for that.

> I'm experiencing less stutters and issues than I was before and the app launches faster than ever.

Good to hear.

**Comment by pikdum** [comment]
Just pushed a fix for the 'Fallout 4 Post-Deploy' script, run the update shortcut to get that.

You'll have to make sure to fix the issues Vortex brings up:
* staging folder location (needs to be on same drive as game)
* deployment method (hardlink)

If mods aren't being downloaded through Vortex, that might be something in your browser settings.
Default behavior in Firefox should be to bring up a list of applications and let you pick.

**Comment by Maz111111** [comment]
Excellent! Many thanks for the quick response!
I reinstalled everything. At first it seemed as if nothing had changed. Then I set the staging folder to the suggested folder (J:\Vortex Mods\{game}) and suddenly I could choose a deployment method (hardlink). Now the modding seems to be working.
Thanks! - Here you should give a hint in the installation instructions.
Regarding the downloads it still doesn't work. No matter which browser.
However, it works if I enter the link manually in vortex and then use the mod manager download link in the internal browser.
It seems that there is something wrong with the communication between vortex and the system browsers.
Maybe this can be repaired somehow.
Another reproducible issue:
After fully installing a mod to post deployment, exiting vortex, switching to GameMode, then launching the game for testing, exiting the game and returning to Desktop Mode, vortex will not launch. It gets stuck on the loading screen after the splash screen. All that helps is restarting the deck.
It seems like not closing vortex and doing the post-deploy without exiting vortex helps. If you then return to desktop mode, vortex is closed - but can be started normally.
Otherwise everything is great!

**Comment by pikdum** [comment]
For the browser download issue, did you try the fixes here? https://github.com/pikdum/steam-deck/issues/10#issuecomment-1566308781

**Comment by Maz111111** [comment]
FYI
The download problem was immediately solved by switching to premium account.
So I don't think, that this was a bug in your development but is a trick from nexus mods
Sorry - but wtf

**Comment by pikdum** [comment]
>  The download problem was immediately solved by switching to premium account.

Interesting. I'll look into this further, definitely possible that I've wired up something wrong and it only works for premium accounts.
Unless Nexus changed something recently.

**Comment by pikdum** [comment]
Reminder for me to look into this:

Example: nxm://fallout4/mods/51369/files/205716

* which flags does STL pass?
* will ./Vortex -d nxm://fallout4/mods/51369/files/205716 work without premium?
* will ./Vortex -i nxm://fallout4/mods/51369/files/205716 work without premium?
* if neither, how does windows handle it?

**Comment by pikdum** [comment]
Going to close this since the original issue was solved.
